language: node_js
node_js:
  - "10"
  - node
sudo: false
 
branches:
  only:
  - "staging"
 
cache:
  directories:
    - node_modules
 
deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api_key: 2de18260-de86-45e7-a867-be5049c39897
  app: atlp-backend-staging